Update RadiomicsCriteria IG
arkhn/arkhn-ig-osiris pull request #290
Opened 2022-11-02 15:48 UTC by MaelleBaillet5

Fix #52 
Fix #54 
Fix #56 
Fix #58 
Fix #60 
Fix #62 
Fix #64

2022-11-08 07:58 UTC, MaelleBaillet5 commented
Fix #66 
Fix #68 
Fix #70 
Fix #72 
Fix #74 
Fix #76 
Fix #78 
Fix #80 
Fix #82

2022-11-15 13:39 UTC, emmaco123 commented on input/fsh/SD_RadiomicsCriteria.fsh
> +Expression:  "extension[localizationMethod].valueCoding != 'Local' implies extension[windowMatrix].valueString.exists()"
à vérifier si pas d'erreur sur cette ligne si = local

2022-11-15 13:51 UTC, emmaco123 commented on input/fsh/SD_RadiomicsCriteria.fsh
> +* extension[localizationMethod].valueCoding from VSLocalizationMethod (required)
où est le fichier vslocalizationmethod

2022-11-15 14:08 UTC, emmaco123 requested changes

2022-11-15 14:08 UTC, emmaco123 commented on input/fsh/SD_RadiomicsCriteria.fsh
> +Expression:  "extension[localizationMethod].valueCoding != 'Local' implies extension[windowMatrix].valueString.exists()"
à vérifier si pas d'erreur sur cette ligne si = local

2022-11-23 12:35 UTC, MaelleBaillet5 commented on input/fsh/SD_RadiomicsCriteria.fsh
> +* extension[localizationMethod].valueCoding from VSLocalizationMethod (required)
Je ne comprends pas. VSlocalizationMethod est un valueset qui se trouve dans le fichier VS_Radiomics.fsh regroupant l'ensemble des Valueset de radiomics.

2022-11-23 12:36 UTC, MaelleBaillet5 commented on input/fsh/SD_RadiomicsCriteria.fsh
> +Expression:  "extension[localizationMethod].valueCoding != 'Local' implies extension[windowMatrix].valueString.exists()"
Fix dans le prochain commit

2022-12-14 14:54 UTC, merged