Update RadiomicsFeature IG
arkhn/arkhn-ig-osiris pull request #295
Opened 2022-11-08 10:19 UTC by MaelleBaillet5

Fix #98 
Fix #100 
Fix #102

2022-11-15 14:19 UTC, emmaco123 requested changes
nous prévenir quand ajout CS_Iimaging et vs_radiomics

2022-11-15 14:19 UTC, emmaco123 commented on input/fsh/SD_RadiomicsFeature.fsh
> +* code.coding.code 0..1 // Obligatory but miissing in pivot
nous rappeler pourquoi variable absente du pivot.

2022-11-15 14:19 UTC, emmaco123 commented on input/fsh/SD_RadiomicsFeature.fsh
> +* valueQuantity.value only decimal
s'agit-il bien du type de  la valeur "code"?

2022-11-23 12:49 UTC, MaelleBaillet5 commented on input/fsh/SD_RadiomicsFeature.fsh
> +* code.coding.code 0..1 // Obligatory but miissing in pivot
La colonne a maintenant été ajouté dans le fichier pivot mais elle a été rempli par des 0 et non par les codes correspondants. Nous sommes en attente des codes pour transformer cette variable en obligatoire et créer le valueset comprenant l'ensemble des codes et leur display.

2022-11-23 12:55 UTC, MaelleBaillet5 commented on input/fsh/SD_RadiomicsFeature.fsh
> +* valueQuantity.value only decimal
Non il s'agit bien de la valeur attribuée à la variable IBSI correspondante. Par exemple, on pourrait s'intéresser à la variable IBSI "Distance" (variable fictive). Sa value pourrait par exemple être 2.05.  
Il s'agit de l'item 3.3 du pdf.

2022-12-13 14:02 UTC, merged