Update Radioimagery ImagingStudy
arkhn/arkhn-ig-osiris pull request #306
Opened 2022-12-14 17:55 UTC by MaelleBaillet5

## Fixes

Fixes #[issue number] by @[issue author]

## Description

## Technical details

## Definition of Done

- [ ] I followed the [Arkhn Code Book](https://www.notion.so/arkhn/Arkhn-Code-Book-23ac18a8af7343d0a3f61f1c9ef7400c) (I swear!).
- [ ] I have written tests for the code I added or updated.
- [ ] I have updated the documentation according to my changes.
- [ ] I have updated the deployment configuration if needed.

## Tests

2022-12-22 14:38 UTC, emmaco123 requested changes

2022-12-22 14:38 UTC, emmaco123 commented on input/fsh/SD_ImagingStudy.fsh
>      patient_orientation 0..1 MS and
#202 caractere optionnel

2022-12-22 14:38 UTC, emmaco123 commented on input/fsh/SD_ImagingStudy.fsh
> +* extension[dx_image].extension[kvp].value[x] only integer
#204 manque cardinalité obligatoire

2022-12-22 14:38 UTC, emmaco123 commented on input/fsh/SD_ImagingStudy.fsh
> +* extension[dx_image].extension[exposure_time].value[x] only integer
#206 manque cardinalité obligatoire

2022-12-22 14:38 UTC, emmaco123 commented on input/fsh/SD_ImagingStudy.fsh
> +* extension[dx_image].extension[exposure_time].value[x] only integer
#208 manque cardinalité

2022-12-22 17:18 UTC, emmaco123 requested changes

2022-12-22 17:18 UTC, emmaco123 commented on input/fsh/SD_ROISegmentation.fsh
> +* identifier[roi] ^short = "Unique identifier ROI"
#216  cardinalité absente et chaine de caractère

2022-12-22 17:18 UTC, emmaco123 commented on input/fsh/SD_ROISegmentation.fsh
> +* code ^definition = "Type of ROI (e.g. RTStruct, binary mask)."
#222 type de variable absente

2022-12-22 17:18 UTC, emmaco123 commented on input/fsh/SD_ROISegmentation.fsh
> +* text MS
#218 : manque type de variable

2022-12-22 17:18 UTC, emmaco123 commented on input/fsh/SD_ROISegmentation.fsh
> +* note 0..1
#220 : manque type de variable

2022-12-22 17:18 UTC, emmaco123 commented on input/fsh/SD_ROISegmentation.fsh
> +* identifier[file] ^short = "File identifier"
#224 : manque cardinalité, type de variable

2022-12-22 17:19 UTC, emmaco123 requested changes
commentaires

2023-01-02 16:57 UTC, MaelleBaillet5 commented on input/fsh/EX_ImagingInjection.fsh
> +* effectiveDateTime = "1000-01-01"
Si les attributs sont optionnels, ils peuvent être absent ce qui est le cas dans cet exemple.

2023-01-02 17:01 UTC, MaelleBaillet5 commented on input/fsh/SD_ImagingEndPoint.fsh
> +* name ^definition = "Study storage location (PACS, web server etc)."
La ressource ImagingStudy (fichier sd_ImagingStudy) fait référence à la ressource Endpoint (sd_ImagingEndpoint).
Dans FHIR, une ressource spécifique est crée dans pour cette variable d'où son utilisation.
Est ce que cela répond à ta question?

2023-01-02 17:10 UTC, MaelleBaillet5 commented on input/fsh/SD_ImagingInjection.fsh
> +* effective[x] 1..1
Modification réalisée.

2023-01-02 17:12 UTC, MaelleBaillet5 commented on input/fsh/SD_ImagingInjection.fsh
> +* effectivePeriod.start ^definition = "Start of the injection for contrast agents. Dicom Tag (0018,1043)"
Modification réalisée

2023-01-02 17:15 UTC, MaelleBaillet5 commented on input/fsh/SD_ImagingInjection.fsh
> +* dosage.dose ^short = "Total amount of radionuclide injected"
Modifié en "Radiopharmaceutical dose" pour être en accord avec le pdf

2023-01-02 17:17 UTC, MaelleBaillet5 commented on input/fsh/SD_ImagingInjection.fsh
> +* effectiveDateTime -> "Dicom Tag (0018,1072)"
Le dicom Tag de l'item 4.5 est bien "Dicom Tag (0018,1072)".
dicom 0018, 1042 correspond à celui effectivePeriod.start qui est correct dans le mapping

2023-01-02 17:21 UTC, MaelleBaillet5 commented on input/fsh/SD_ImagingInjectionmedication.fsh
> +* code.text ^definition = "Name of the radiopharmaceutical (Dicom Tag (0018,0031)) or the contrast agent (Dicom Tag (0018,0010)). This variable is mandatory only if the series is PT."
Car dans les 2 items, il s'agit d'une injection mais celle-ci peut être un agent de contraste en cas de radio, scan ou IRM ou un produit radiopharmaceutique en cas d'imagerie nucléaire/pet-scan.  Il n'est pas possible d'avoir les 2 en même temps. L'attribut code de cette ressource correspond au produit injecté qui peut correspondre à ces 2 items en fonction du type d'imagerie.

2023-01-02 17:27 UTC, MaelleBaillet5 commented on input/fsh/SD_ImagingStudy.fsh
> +* numberOfSeries ^definition = "Number of series contained in the study. Dicom Tag (0020, 1206)"
Issue crée et ajoutée à la PR (issue 316)

2023-01-02 17:32 UTC, MaelleBaillet5 commented on input/fsh/SD_ImagingStudy.fsh
> +* series.modality ^definition = "Type of equipment used to acquire data for the series. Dicom Tag (0008, 0060)"
Ce fichier n'est pas le bon.
Si tu regardes le fichier ici: https://github.com/arkhn/arkhn-ig-osiris/blob/RadioimageryImagingStudy/input/fsh/SD_ImagingStudy.fsh, l'item est bien correct.

A @ummmaar, as tu une idée de pourquoi la PR ne correspond pas à la dernière version?

2023-01-02 17:41 UTC, MaelleBaillet5 commented on input/fsh/SD_ImagingStudy.fsh
>  * extension[pixel_spacing].value[x] only string
Ajout des dicom pour les item 5.2, 5.3, 5.5 et 5.6
L'item 5.2 (#154) est bien présent: "slice_thickness"

2023-01-02 17:43 UTC, MaelleBaillet5 commented on input/fsh/SD_ImagingStudy.fsh
>      patient_orientation 0..1 MS and
Cet attribut est bien optionnel dans le pdf et dans le code ci dessus (0..1 = optionnel)

2023-01-02 17:46 UTC, MaelleBaillet5 commented on input/fsh/SD_ImagingStudy.fsh
> +    kvp 1..1 MS and
Cette ligne correspond à l'item 9.3 et non 7.1. Il est bien optionnel. Cet attribut est présent à la fois dans la modalité DX (ici) où il est obligatoire et dans la modalité ct (item 7.1) où il est optionnel.

2023-01-02 17:47 UTC, MaelleBaillet5 commented on input/fsh/SD_ImagingStudy.fsh
> +* extension[dx_image].extension[kvp].value[x] only integer
La cardinalité est correct: cf ligne 280

2023-01-02 17:47 UTC, MaelleBaillet5 commented on input/fsh/SD_ImagingStudy.fsh
> +* extension[dx_image].extension[exposure_time].value[x] only integer
La cardinalité est correct: cf ligne 281

2023-01-02 17:47 UTC, MaelleBaillet5 commented on input/fsh/SD_ImagingStudy.fsh
> +* extension[dx_image].extension[exposure_time].value[x] only integer
La cardinalité est correct: cf ligne 282

2023-01-02 17:59 UTC, MaelleBaillet5 commented on input/fsh/SD_ImagingStudy.fsh
> +* series.number -> "Dicom Tag (0020,0011)"
Le dicom Tag de l'item 1.7 se situe à la ligne 407. Il a été modifié car il était effectivement incorrect (le nom de l'item+le dicom Tag)

2023-01-02 18:06 UTC, MaelleBaillet5 commented on input/fsh/SD_ROISegmentation.fsh
> +* identifier[roi] ^short = "Unique identifier ROI"
Cardinalité obligatoire présente ligne 20 et string par défaut (plus exactement identifier)

2023-01-02 18:06 UTC, MaelleBaillet5 commented on input/fsh/SD_ROISegmentation.fsh
> +* text MS
Présente par défaut

2023-01-02 18:07 UTC, MaelleBaillet5 commented on input/fsh/SD_ROISegmentation.fsh
> +* note 0..1
Présente par défaut

2023-01-02 18:07 UTC, MaelleBaillet5 commented on input/fsh/SD_ROISegmentation.fsh
> +* code ^definition = "Type of ROI (e.g. RTStruct, binary mask)."
Présente par défaut (string dans le pdf mais modifié volontairement en code)

2023-01-02 18:08 UTC, MaelleBaillet5 commented on input/fsh/SD_ROISegmentation.fsh
> +* identifier[file] ^short = "File identifier"
Cardinalité obligatoire présente ligne 20 et string par défaut (plus exactement identifier)

2023-01-03 10:44 UTC, emmaco123 commented on input/fsh/SD_ImagingStudy.fsh
> +* numberOfSeries ^definition = "Number of series contained in the study. Dicom Tag (0020, 1206)"
merci

2023-01-03 10:46 UTC, emmaco123 commented on input/fsh/SD_ImagingStudy.fsh
> +* series.number -> "Dicom Tag (0020,0011)"
tu laisses les lignes 407 et 409 ou tu supprimes la ligne 409?

2023-01-03 10:50 UTC, emmaco123 commented on input/fsh/SD_ImagingInjectionmedication.fsh
> +* code.text ^definition = "Name of the radiopharmaceutical (Dicom Tag (0018,0031)) or the contrast agent (Dicom Tag (0018,0010)). This variable is mandatory only if the series is PT."
ok merci

2023-01-03 10:51 UTC, emmaco123 commented on input/fsh/SD_ImagingInjection.fsh
> +* dosage.dose ^short = "Total amount of radionuclide injected"
ok

2023-01-03 11:01 UTC, emmaco123 approved these changes

2023-01-03 13:58 UTC, MaelleBaillet5 commented on input/fsh/SD_ImagingInjection.fsh
> +* effective[x] 1..1
J'ai du remettre medication et effective en obligatoire car cela est imposé par le standard FHIR. Cependant le caractère optionnel est toujours présent car cette ressource est référencé dans imagingstudy où elle est bien optionnelle.

2023-01-06 15:29 UTC, merged